# Generated by Django 4.2.1 on 2023-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
