# Generated by Django 4.2.1 on 2023-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_log_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parentID',
        ),
        migrations.AddField(
            model_name='category',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
