# Generated by Django 4.2.1 on 2023-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_remove_category_parentid_category_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='learnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
